-- Enchanted Hub Leaks (iblameaabis special)

loadstring(game:HttpGet("https://void-hub-byvoiddevs.vercel.app/scripts/leaks/Muscle%20Legends/Enchanted%20Hub/PaidVersion.luau"))()

loadstring(game:HttpGet("https://void-hub-byvoiddevs.vercel.app/scripts/leaks/Muscle%20Legends/Enchanted%20Hub/RegularVersion.luau"))()

loadstring(game:HttpGet("https://void-hub-byvoiddevs.vercel.app/scripts/leaks/Ninja%20Legends/Enchanted%20Hub/ninja.luau"))()

loadstring(game:HttpGet("https://void-hub-byvoiddevs.vercel.app/scripts/leaks/Steal%20A%20Brainrot/Enchanted%20Hub/sab.luau"))()

loadstring(game:HttpGet("https://void-hub-byvoiddevs.vercel.app/scripts/leaks/Legends%20of%20Speed/Enchanted%20Hub/los.lua"))()
